begin;
do $$
declare owner_id uuid; admin_id uuid; rider_id uuid; stable uuid; horse uuid; agreement uuid; old_assignment uuid; future_assignment uuid; feed uuid; n int;
begin
 select id into owner_id from public.profiles order by id limit 1;
 select id into admin_id from public.profiles where id<>owner_id order by id limit 1;
 rider_id := admin_id;
 if rider_id is null then raise exception 'Two existing profiles required'; end if;
 insert into public.stables(name) values('Rollback member departure test') returning id into stable;
 insert into public.memberships(stable_id,user_id,role) values(stable,owner_id,'owner'),(stable,rider_id,'rider');
 insert into public.horses(stable_id,name) values(stable,'Test horse') returning id into horse;
 insert into public.horse_assignments(stable_id,user_id,horse_id,assignment_date) values(stable,rider_id,horse,current_date-1) returning id into old_assignment;
 insert into public.horse_assignments(stable_id,user_id,horse_id,assignment_date) values(stable,rider_id,horse,current_date+2) returning id into future_assignment;
 insert into public.feeding_shifts(stable_id,shift_date,shift_time,label,assigned_to,original_assigned_to) values(stable,current_date+1,'08:00','Morgenfôring',rider_id,rider_id) returning id into feed;
 insert into public.recurring_horse_assignments(stable_id,user_id,horse_id,weekday,week_parity) values(stable,rider_id,horse,6,0) returning id into agreement;
 insert into public.feeding_swap_requests(stable_id,shift_id,from_user,to_user,status) values(stable,feed,rider_id,owner_id,'pending');
 perform set_config('request.jwt.claim.sub',rider_id::text,true);execute 'set local role authenticated';
 update public.memberships set active=false where stable_id=stable and user_id=admin_id;
 get diagnostics n=row_count;if n<>0 then raise exception 'Rider could remove admin'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 update public.memberships set role='admin' where stable_id=stable and user_id=rider_id;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 begin update public.memberships set active=false where stable_id=stable and user_id=owner_id;raise exception 'Owner removed';exception when insufficient_privilege then null;end;
 begin update public.memberships set active=false where stable_id=stable and user_id=admin_id;raise exception 'Self removed';exception when insufficient_privilege then null;end;
 begin update public.memberships set role='owner' where stable_id=stable and user_id=rider_id;raise exception 'Admin promoted user';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 update public.memberships set role='rider' where stable_id=stable and user_id=rider_id;
 update public.memberships set active=false where stable_id=stable and user_id=rider_id;
 if (select active from public.recurring_horse_assignments where id=agreement) then raise exception 'Agreement still active'; end if;
 if not(select is_cancelled from public.horse_assignments where id=future_assignment) then raise exception 'Future date still active'; end if;
 if (select assigned_to from public.feeding_shifts where id=feed) is not null then raise exception 'Feeding not released'; end if;
 if (select original_assigned_to from public.feeding_shifts where id=feed)<>rider_id then raise exception 'Feeding history lost'; end if;
 if (select count(*) from public.tasks where assignment_id=old_assignment)<>5 then raise exception 'History lost'; end if;
 if exists(select 1 from public.feeding_swap_requests where stable_id=stable and status='pending') then raise exception 'Pending swap retained'; end if;
 perform set_config('request.jwt.claim.sub',rider_id::text,true);
 if public.is_member(stable) then raise exception 'Departed user still member'; end if;
 if exists(select 1 from public.tasks where stable_id=stable) then raise exception 'Departed user reads stable'; end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 update public.memberships set active=true where stable_id=stable and user_id=rider_id;
 if (select active from public.recurring_horse_assignments where id=agreement) then raise exception 'Restoration restarted agreement'; end if;
 update public.feeding_shifts set assigned_to=rider_id where id=feed;
 if (select assigned_to from public.feeding_shifts where id=feed)<>rider_id then raise exception 'Reassignment failed'; end if;
 update public.memberships set role='admin' where stable_id=stable and user_id=admin_id;
 update public.memberships set active=false where stable_id=stable and user_id=admin_id;
 if (select active from public.memberships where stable_id=stable and user_id=admin_id) then raise exception 'Owner cannot remove administrator'; end if;
end;
$$;
rollback;
